name: Build V3 - Version and release on PR

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Create Pull Request
        id: cpr
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref_name }}
          target_branch: master

      - name: Label changes
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.cpr.outputs.pr_number }}
          sync-labels: true
      - name: Get Labels Action
        uses: snnaplab/get-labels-action@v1.0.1
        with:
          number: ${{ steps.cpr.outputs.pr_number }}
            
      - name: Bump version and push tag
        if: contains(fromJSON(env.LABELS), 'audio')
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          release_branches: master
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_prerelease_bump: patch
          tag_prefix: ''
      - name: Release Changelog Builder
        if: contains(fromJSON(env.LABELS), 'audio')
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5.0.0
        with:
          # fromTag: ${{ steps.tag_version.outputs.new_version }}
          # toTag: ${{ steps.tag_version.outputs.new_version }}
          outputFile: "CHANGELOG.MD"
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: "COMMIT"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                "categories": [
                  {
                    "title": "## üéπ Audio",
                    "labels": ["audio", "sound", "sounds"]
                  },
                  {
                    "title": "## üêõ Fixes",
                    "labels": ["fix", "fixes"]
                  },
                  {
                    "title": "## üî© CI/CD (you don't care)",
                    "labels": ["ci"]
                  },
                  {
                    "key": "tests",
                    "title": "## üß™ Tests",
                    "labels": ["test", "tests"]
                  }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|fixes|perf|refactor|revert|style|test|tests|audio|sound|sounds){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }
      - name: See CHANGELOG
        if: contains(fromJSON(env.LABELS), 'audio')
        run: |
          echo "${{steps.changelog.outputs.changelog}}"

      - name: Release
        if: contains(fromJSON(env.LABELS), 'audio')
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.tag_version.outputs.new_version }}
          tag_name: ${{ steps.tag_version.outputs.new_version }}
          body: ${{steps.changelog.outputs.changelog}}
          body_path: CHANGELOG.MD
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          make_latest: true